import "./theme/global.css";

export * from "./theme";

export * from "./components";
export {
  // Core
  ConfigProvider,
  theme,
  type ThemeConfig,

  // Layout
  Layout,
  Grid,
  Row,
  Col,
  Space,
  Divider,
  Flex,

  // Navigation
  Menu,
  type MenuProps,
  Breadcrumb,
  type BreadcrumbProps,
  Pagination,
  type PaginationProps,
  Steps,
  type StepsProps,
  Anchor,
  type AnchorProps,

  // Data Entry
  Form,
  type FormProps,
  InputNumber,
  type InputNumberProps,
  Select,
  type SelectProps,
  TreeSelect,
  type TreeSelectProps,
  Cascader,
  type CascaderProps,
  DatePicker,
  type DatePickerProps,
  TimePicker,
  type TimePickerProps,
  Calendar,
  type CalendarProps,
  Upload,
  type UploadProps,
  Transfer,
  type TransferProps,
  Slider,
  Rate,
  type RateProps,
  Mentions,
  type MentionsProps,
  AutoComplete,
  type AutoCompleteProps,
  ColorPicker,
  type ColorPickerProps,

  // Data Display
  Table,
  type TableProps,
  Progress,
  type ProgressProps,
  Tree,
  type TreeProps,
  Timeline,
  type TimelineProps,
  Collapse,
  type CollapseProps,
  Carousel,
  type CarouselProps,
  Avatar,
  type AvatarProps,
  Badge,
  type BadgeProps,
  Descriptions,
  type DescriptionsProps,
  Empty,
  type EmptyProps,
  Image,
  type ImageProps,
  List,
  type ListProps,
  Popover,
  type PopoverProps,
  Statistic,
  type StatisticProps,
  Skeleton,
  type SkeletonProps,
  QRCode,
  type QRCodeProps,

  // Feedback
  Alert,
  type AlertProps,
  Drawer,
  type DrawerProps,
  Modal,
  type ModalProps,
  message,
  notification,
  Popconfirm,
  type PopconfirmProps,
  Spin,
  type SpinProps,
  Result,
  type ResultProps,

  // General
  FloatButton,
  type FloatButtonProps,

  // Other
  Affix,
  type AffixProps,
  BackTop,
  type BackTopProps,
  Dropdown,
  type DropdownProps,
  Tooltip,
  type TooltipProps,
  Tour,
  type TourProps,
  Watermark,
  type WatermarkProps,
} from "antd";

export { Button as AntButton, type ButtonProps as AntButtonProps } from "antd";

export * as LucideIcons from "lucide-react";
