import { render, screen } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import { Avatar } from "./Avatar";

Object.defineProperty(window, "matchMedia", {
  writable: true,
  value: vi.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

class ResizeObserverMock {
  observe() {}
  unobserve() {}
  disconnect() {}
}

// @ts-expect-error test environment polyfill
global.ResizeObserver = ResizeObserverMock;

describe("Avatar", () => {
  it("renders with initials", () => {
    render(<Avatar>CN</Avatar>);
    expect(screen.getByText("CN")).toBeInTheDocument();
  });

  it("renders image with cover fit when src is provided", () => {
    render(<Avatar src="https://example.com/img.jpg" alt="avatar" />);

    const img = screen.getByRole("img", { name: "avatar" });
    expect(img).toHaveStyle({ objectFit: "cover" });
    expect(img).toHaveAttribute("draggable", "false");
  });

  it("blocks text selection on root avatar", () => {
    const { container } = render(<Avatar>CN</Avatar>);
    const root = container.firstChild as HTMLElement;

    expect(root).toHaveStyle({ userSelect: "none" });
  });

  it("applies small size styling", () => {
    const { container } = render(<Avatar dsSize="small">S</Avatar>);
    // Class names are generated by CSS-in-JS, difficult to test.
    // We can check if the inline style or specific ant classes are present if we knew them.
    // For now, snapshot or basic existing check.
    expect(container.firstChild).toBeInTheDocument();
  });
});
